id: P005567
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG25359
  title: སྒྲ་རིག་པའི་བསླབ་གཞི། ༼དག་བཅོས་མ།༽
  author: ''
  volumes:
    26575c8e732e4e05b9d7f712922a7720:
      image_group_id: I1KG25361
      title: ''
      volume_number: 1
      total_pages: 234
      base_file: v001.txt
