id: I7AA6BB5A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T02:58:34+00:00'
last_modified: '2022-06-08T04:58:23.361611+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG25359
  title: སྒྲ་རིག་པའི་བསླབ་གཞི། ༼དག་བཅོས་མ།༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    EBF7:
      image_group_id: I1KG25361
      title: ''
      total_pages: 234
      order: 1
      base_file: EBF7.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
